#!/bin/bash

set -ex

cpi_name="openstack"
cpi_dir=$(cd $(dirname $0)/../ && pwd)
cpi_gems_dir=${cpi_dir}/src/bosh_${cpi_name}_cpi

cleanup() {
  cd $cpi_gems_dir
  rm Gemfile*
}

trap cleanup EXIT

. ./helpers.sh

# !! eventmachine-1.0.7.gem
# !! nokogiri-1.6.6.2.gem

download_sources nokogiri 1.6.6.2 https://github.com/sparklemotion/nokogiri/archive/v1.6.6.2.tar.gz
download_sources libxml2 2.9.2 ftp://ftp.xmlsoft.org/libxml2/libxml2-2.9.2.tar.gz
download_sources libxslt 1.1.28 ftp://ftp.xmlsoft.org/libxml2/libxslt-1.1.28.tar.gz
download_sources eventmachine 1.0.7 https://github.com/eventmachine/eventmachine/archive/v1.0.7.tar.gz

update_package_configs libxml2 2.9.2
update_package_configs libxslt 1.1.28

set_environment_variables nokogiri '1.6.6.2'
unarchive_package
go_to_build_folder
patch -p1 < $assets_folder/nokogiri-1.6.6.2.patch
gem install bundler
bundle install
rake gem # or rake gem:package
# cp pkg/$full_package_name.gem $build_package/dea_next_gems/vendor/cache

# eventmachine-0.12.10
set_environment_variables eventmachine '1.0.7'
unarchive_package
go_to_build_folder
patch -p1 < $assets_folder/dea_next_gems/eventmachine-1.0.7.patch
gem build eventmachine.gemspec
# cp $full_package_name.gem $build_package/dea_next_gems/vendor/cache





(
  cd $cpi_gems_dir
  cat > 'Gemfile' <<EOF
source "https://rubygems.org"

gem "bosh_${cpi_name}_cpi"
EOF

  bundle package
)
